//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiferentesPruebas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVATE_TOKEN
    {
        public long ID { get; set; }
        public long ID_USER { get; set; }
        public string ACTIVATE_TOKEN1 { get; set; }
        public long CREATED_USER_ID { get; set; }
        public Nullable<long> MODIFIED_USER_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public byte DELETED { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
