//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiferentesPruebas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVATE_TOKEN> ACTIVATE_TOKEN { get; set; }
        public virtual DbSet<PSP> PSP { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SHOP> SHOP { get; set; }
        public virtual DbSet<SUSCRIBER> SUSCRIBER { get; set; }
        public virtual DbSet<SUSCRIBER_CONFIG> SUSCRIBER_CONFIG { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
