//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiferentesPruebas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOP
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal LATITUDE { get; set; }
        public decimal LONGITUDE { get; set; }
        public Nullable<decimal> ACCURACY { get; set; }
        public Nullable<decimal> ALTITUDE { get; set; }
        public long CREATED_USER_ID { get; set; }
        public Nullable<long> MODIFIED_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<byte> DELETED { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
    }
}
