//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiferentesPruebas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSCRIBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUSCRIBER()
        {
            this.USER = new HashSet<USER>();
            this.SUSCRIBER_CONFIG = new HashSet<SUSCRIBER_CONFIG>();
            this.USER1 = new HashSet<USER>();
        }
    
        public long ID { get; set; }
        public long ID_PSP { get; set; }
        public string NAME { get; set; }
        public string CBU { get; set; }
        public long CREATED_USER_ID { get; set; }
        public Nullable<long> MODIFIED_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public byte DELETED { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
    
        public virtual PSP PSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSCRIBER_CONFIG> SUSCRIBER_CONFIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USER1 { get; set; }
    }
}
