//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiferentesPruebas
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.ACTIVATE_TOKEN1 = new HashSet<ACTIVATE_TOKEN>();
        }
    
        public long ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public long CREATED_USER_ID { get; set; }
        public Nullable<long> MODIFIED_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public byte DELETED { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public byte ENABLED { get; set; }
        public byte[] PHOTO_IMAGE { get; set; }
        public string PHOTO_FILENAME { get; set; }
        public Nullable<long> ID_SUSCRIBER { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<long> ACTIVATE_TOKEN { get; set; }
        public string ALIAS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVATE_TOKEN> ACTIVATE_TOKEN1 { get; set; }
        public virtual SUSCRIBER SUSCRIBER { get; set; }
        public virtual SUSCRIBER SUSCRIBER1 { get; set; }
    }
}
